### ISSUE TITLE
Steps to add typings

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/office-js-docs#846]
Article:
Tips for creating Office Add-ins with Angular 2
https://dev.office.com/docs/add-ins/develop/add-ins-with-angular2

Issue: 
Please add the info about where we can find and install the typing files. Thanks
![image](https://cloud.githubusercontent.com/assets/3375461/25294746/91b7e374-2695-11e7-88dc-64a0ca884139.png)

**Comment by WrathOfZombies** [comment]
You can use `@types/office-js`. @siewmoi is working on an TypeScript article that will explain this step.

**Comment by Hongbo-Miao** [comment]
Just leave a quick solution here in case someone else need it right now.
```
npm install --save-dev @types/office-js
```

**Comment by Rick-Kirkham** [comment]
Fixed in the source document. Should be public in a few days.

**Comment by troywweber7** [comment]
@WrathOfZombies I have PhpStorm and have installed @types/office-js but it is still not recognizing the types. References like `Excel` are showing up white (which is not the color I have for namespaces)...

**Comment by troywweber7** [comment]
@WrathOfZombies well, I don't know exactly what I did. But I tried invalidating PhpStorm's cache and restarting, and made sure I added the appropriate triple-slash reference to the typings.d.ts file and now everything is showing up as required.
